#!/bin/bash

# Your username
username='da'

# Directory containing your music files
mpd_zik_dir='/home/musique'

# Directories to be created in /mnt/
mountpoints='canon groar nexus win win2'

# You should know what you are doing!
install_nvidia=1
use_optional=1

# DO NOT EDIT THIS FILE FROM HERE (at ur own risk!)

if [ $(whoami) != 'root' ]; then
    echo 'Please run me when logged as root.' > /dev/stderr
    exit 1
fi

cp -f etc/fstab /etc/fstab
for directory in $mountpoints; do
    echo "Creating /mnt/$directory directory."
    mkdir "/mnt/$directory"
    echo "/mnt/$directory" >> /etc/fstab
done

echo '# Set /home and / (below) + /mnt/ mountpoints (above)' >> /etc/fstab
blkid | sed 's/^/# /gi' >> /etc/fstab

# Sudo
aptitude -y install sudo
# The password is no more required
echo "$username	ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

# Install ViM
aptitude -y install vim vim-syntax-go

echo 'Will now edit /etc/fstab. You have to set /home + /mnt/* (ur mountpoints)'
echo 'You have just one try; when exiting from ViM, it will be done.'
echo '--- PRESS ENTER WHEN READY ---'
read
vi /etc/fstab

echo -n 'Remount /home ? [Y/n]'
response=$(get_word Y)
if [ $response != "n" ]; then
    # Useless.. unless you want to gain a little disk space..
    rm -rf /home; mkdir /home
    mount /home
fi

# Install graphical part
aptitude -y install xserver-xorg xinit
aptitude -y install openbox python-xdg conky-std
aptitude -y install feh graphicsmagick-imagemagick-compat
aptitude -y install obmenu obconf thunar
aptitude -y install numlockx volumicon-alsa xcalib xscreensaver tint2 wbar

cp -f .bashrc '/root/.bashrc'
echo -n "Copy default config. files to your $HOME? (allow overwrite) [Y/n] "
response=$(get_word Y)
if [ $response != "n" ]; then
    cp -f .bashrc "/home/$username/.bashrc"
    cp -f .wbar "/home/$username/.wbar"
    cp -f .xinitrc "/home/$username/.xinitrc"
    cp -f .xscreensaver "/home/$username/.xscreensaver"
    cp -f .xsession "/home/$username/.xsession"
    cp -f .conkyrc "/home/$username/.conkyrc"
    mkdir -p "/home/$username/.config"
    cp -rf etc/.config/{autostart,openbox,volumeicon} "/home/$username/.config/"
fi

# Install the terminal
aptitude -y install rxvt-unicode

# Install musical part
aptitude -y install sonata mpd mpc
sed 's#^music_directory.*$#music_directory "'$mpd_zik_dir'"#' etc/mpd.conf > /etc/mpd.conf

# Autologin
aptitude -y install mingetty
sed 's/--autologin \w*/--autologin '$username'/' etc/inittab > /etc/inittab

# Propose a package to install whenever a command is not found
aptitude -y install command-not-found && echo 'Do not worry about that dude, I and I take care of it' && update-command-not-found

# Install Web browsers
# This is firefox
aptitude -y install iceweasel
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# Dependencies for Chrome
aptitude -y install libgconf2-4 libxss1 xdg-utils
dpkg -i google-chrome-stable_current_amd64.deb
rm -f google-chrome-stable_current_amd64.deb

# Video players
aptitude -y install mplayer vlc

# FTP client
aptitude -y install lftp

# Install eog (image viewer)
aptitude -y install eog

# News reader
aptitude -y install slrn

# IRC client
aptitude -y install irssi

# PDF reader
aptitude -y install evince

# Git
aptitude -y install gitk

# Sound
aptitude -y install alsa-utils

# smartctl (for HDD health check)
aptitude -y install smartmontools

if [ $install_nvidia -eq 1 ]; then
    # NVIDIA proprietary drivers
    aptitude -y install nvidia-glx nvidia-xconfig
fi

if [ $use_optional -eq 1 ]; then
    # Optional stuff from here

    # Crypted USB key (alias crypt)
    aptitude -y install cryptsetup
    cp -f etc/crypttab /etc/crypttab

    # Galaxy Nexus (alias nexus)
    aptitude -y install mtp-tools

    # Realtek 8169 (Ethernet card)
    aptitude -y install firmware-realtek
fi

echo 'Will now reboot to let you enjoy openbox on debian.'
echo 'Please run `mpc update` after the reboot for your music to be loaded.'
echo 'Peace.'
echo '--- PRESS ENTER WHEN READY ---'
read
reboot

# One argument: default value if nothing was read
function get_word()
{
    read read_tmp
    if [ -z $read_tmp ]; then
        echo $1
    else
        echo $read_tmp
    fi
}
